### ISSUE TITLE
BUG at Home_Screen

### ISSUE THREAD

**Issue by rezaoktaviansandyxx** [rianjanuarian/stylish-shop#145]
aq gatau kenapa ya, klo pas loadingselesai di homescreen, tu klo di scroll ke bawah, jadinya loading lagi...
klo bisa, benerin dong yang itu 😄 
@rianjanuarian @andikatp

**Comment by andikatp** [comment]
kok w engga bang? wkwkwk ss dong

**Comment by andikatp** [comment]
fixed
