### ISSUE TITLE
Issue Deployment

### ISSUE THREAD

**Issue by rezaoktaviansandyxx** [rianjanuarian/stylish-shop#146]
Taruh di sini ya klo ada apa" tentang deployment @rianjanuarian @andikatp

**Comment by rezaoktaviansandyxx** [comment]
@andikatp udah saya deploy

**Comment by andikatp** [comment]
oke

**Comment by andikatp** [comment]
jadi kenapa tuh  column "color" of relation "carts" does not exist, tpi di localhost bsa

**Comment by rezaoktaviansandyxx** [comment]
Gatau bang, kan sudah sesuai dengan deployment yang terakhir lu buat bang @andikatp

**Comment by rezaoktaviansandyxx** [comment]
mungkin dari storagenya, coba export ke saya bang untuk storagenya dari postgres...
@andikatp

**Comment by rezaoktaviansandyxx** [comment]
@andikatp Sudah bisa dicoba ya, bang

**Comment by andikatp** [comment]
nicenicenicenice tqtq

**Comment by rezaoktaviansandyxx** [comment]
@andikatp klo misalnya ada perubahan pada BE-mu, jangan lupa ubah juga di swaggernya...
