### ISSUE TITLE
BUG in cart

### ISSUE THREAD

**Issue by rezaoktaviansandyxx** [rianjanuarian/stylish-shop#159]
kenapa ya ini klo pas aq add ke cart, malah nggak ada di cartnya? @andikatp 

https://github.com/rianjanuarian/stylish-shop/assets/81407568/dd4dc888-6e3c-4aeb-8882-cc0ea0ef1f5e

**Comment by andikatp** [comment]
oh krna g make future builder si itu alasannya, jumatan dulu

**Comment by andikatp** [comment]
aku fix abis jumat jan ubah2 dulu aa

**Comment by andikatp** [comment]
fixed
