### ISSUE TITLE
BUG Avatar Home Screen

### ISSUE THREAD

**Issue by rezaoktaviansandyxx** [rianjanuarian/stylish-shop#167]
https://github.com/rianjanuarian/stylish-shop/assets/81407568/77e460fc-cddc-4f14-94f1-02d5c66c2e5c

@andikatp ini kenapa yah??

**Comment by rezaoktaviansandyxx** [comment]
Sudah fixed sendiri

**Comment by andikatp** [comment]
cuma lambat doang, ntah napa, lgi diluar g bsa cek yahahah gud lah dh fixed
