### ISSUE TITLE
Profile Picture berubah ketika update profile

### ISSUE THREAD

**Issue by andikatp** [rianjanuarian/stylish-shop#185]
profile picture berubah juga ketika tidak mengambil gambar, perasaan dh aku fix, tpi g bsa cek, tolong cek di be keknya be nya
![untitled](https://github.com/rianjanuarian/stylish-shop/assets/78133832/25372dd2-6cb3-4bd6-86c5-30a245fcc883)
![Screenshot 2023-11-28 003806](https://github.com/rianjanuarian/stylish-shop/assets/78133832/7975b83a-a8fd-44f9-a590-12b3e41ab10e)

**Comment by rezaoktaviansandyxx** [comment]
Di gw aman ding @andikatp ...

https://github.com/rianjanuarian/stylish-shop/assets/81407568/547a98ca-6cfa-42ad-bb92-b137db06eee1
