### ISSUE TITLE
Bug Total Price

### ISSUE THREAD

**Issue by rezaoktaviansandyxx** [rianjanuarian/stylish-shop#186]
kmaren dah bener, kenapa jadinya rusak total pricenya @andikatp ??

https://github.com/rianjanuarian/stylish-shop/assets/81407568/e40fdcee-f89d-4947-92a6-2465b3599652

**Comment by rezaoktaviansandyxx** [comment]
udahlah, jangan diubah"

![image](https://github.com/rianjanuarian/stylish-shop/assets/81407568/be536e5a-d474-4820-a3aa-25bd6a10f01d)

![image](https://github.com/rianjanuarian/stylish-shop/assets/81407568/d0e2d794-57b7-4781-8e64-49cc0b9f458b)

**Comment by andikatp** [comment]
bsa diubah itu, cuma logika dkit doang pindahin ke controller aja, aku jam 2 malam g trlihat doang dikit

**Comment by andikatp** [comment]
dh fix
