### ISSUE TITLE
Error transaction

### ISSUE THREAD

**Issue by rezaoktaviansandyxx** [rianjanuarian/stylish-shop#207]
![image](https://github.com/rianjanuarian/stylish-shop/assets/81407568/fdd4ef31-d02c-44c1-9829-799d5b07197d)

![image](https://github.com/rianjanuarian/stylish-shop/assets/81407568/c5a8e044-ab5d-403f-86c0-95847a151228)

@andikatp klo bisa benerin, benerin dah, karena ini dah mepet deadline...

**Comment by andikatp** [comment]
yodah gosah ada item details, trus jg gosah ada history, lgsung tembak dari transaction aja
